# Default Hyperparameters
DEFAULT_LEARNING_RATE = 0.1
DEFAULT_DISCOUNT_FACTOR = 0.99
DEFAULT_EXPLORATION_RATE = 1.0
DEFAULT_EXPLORATION_DECAY = 0.9999
DEFAULT_EPISODES = 20000

# Environment Settings
ENV_NAME = 'FrozenLake-v1'
IS_SLIPPERY = True
MAP_NAME = "4x4"
RENDER_MODE_TEST = "ansi"
